name       : libx11
version    : 1.6.7
release    : 20
source     :
    - https://www.x.org/releases/individual/lib/libX11-1.6.7.tar.bz2 : 910e9e30efba4ad3672ca277741c2728aebffa7bc526f04dcfa74df2e52a1348
license    : MIT
component  : xorg.library
summary    : Core X11 protocol client library
description: |
    Core X11 protocol client library
builddeps  :
    - pkgconfig32(xau)
    - pkgconfig32(xcb)
    - pkgconfig32(xdmcp)
    - pkgconfig32(xtrans)
    - pkgconfig(inputproto)
    - pkgconfig(kbproto)
    - pkgconfig(xextproto)
    - pkgconfig(xf86bigfontproto)
emul32     : yes
optimize   :
    - speed
    - lto
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
