name       : libx11
version    : 1.8.6
release    : 41
source     :
    - https://www.x.org/releases/individual/lib/libX11-1.8.6.tar.gz : 5ff0d26c94d82ebb94a944b9f1f55cd01b9713fd461fe93f62f3527ce14ad94e
license    : MIT
component  : xorg.library
summary    : Core X11 protocol client library
description: |
    Core X11 protocol client library
emul32     : yes
mancompress: yes
optimize   :
    - speed
    - lto
builddeps  :
    - pkgconfig32(xau)
    - pkgconfig32(xcb)
    - pkgconfig32(xdmcp)
    - pkgconfig32(xtrans)
    - pkgconfig(xproto)
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
