name       : libx11
version    : 1.7.4
release    : 33
source     :
    - https://www.x.org/releases/individual/lib/libX11-1.7.4.tar.gz : 252fb028524caa878e6507729efc115d7434f867f6549fe087e7869a66adfa2c
license    : MIT
component  : xorg.library
summary    : Core X11 protocol client library
description: |
    Core X11 protocol client library
emul32     : yes
optimize   :
    - speed
    - lto
builddeps  :
    - pkgconfig32(xau)
    - pkgconfig32(xcb)
    - pkgconfig32(xdmcp)
    - pkgconfig32(xtrans)
    - pkgconfig(xproto)
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
