name       : libx11
version    : 1.7.2
release    : 29
source     :
    - https://www.x.org/releases/individual/lib/libX11-1.7.2.tar.gz : 2c26ccd08f43a6214de89110554fbe97c71692eeb7e7d4829f3004ae6fafd2c0
license    : MIT
component  : xorg.library
summary    : Core X11 protocol client library
description: |
    Core X11 protocol client library
emul32     : yes
optimize   :
    - speed
    - lto
builddeps  :
    - pkgconfig32(xau)
    - pkgconfig32(xcb)
    - pkgconfig32(xdmcp)
    - pkgconfig32(xtrans)
    - pkgconfig(xproto)
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
