name       : libx11
version    : 1.6.6
release    : 19
source     :
    - https://www.x.org/releases/individual/lib/libX11-1.6.6.tar.bz2 : 65fe181d40ec77f45417710c6a67431814ab252d21c2e85c75dd1ed568af414f
license    : MIT
component  : xorg.library
summary    : Core X11 protocol client library
description: |
    Core X11 protocol client library
builddeps  :
    - pkgconfig32(xau)
    - pkgconfig32(xcb)
    - pkgconfig32(xdmcp)
    - pkgconfig32(xtrans)
    - pkgconfig(inputproto)
    - pkgconfig(kbproto)
    - pkgconfig(xextproto)
    - pkgconfig(xf86bigfontproto)
emul32     : yes
optimize   :
    - speed
    - lto
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
