name       : libx11
version    : 1.8.4
release    : 40
source     :
    - https://www.x.org/releases/individual/lib/libX11-1.8.4.tar.gz : efd3a3a43c1f177edc2c205bedb0719b6648203595e54c0b83a32576aeaca7cd
license    : MIT
component  : xorg.library
summary    : Core X11 protocol client library
description: |
    Core X11 protocol client library
emul32     : yes
mancompress: yes
optimize   :
    - speed
    - lto
builddeps  :
    - pkgconfig32(xau)
    - pkgconfig32(xcb)
    - pkgconfig32(xdmcp)
    - pkgconfig32(xtrans)
    - pkgconfig(xproto)
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
