name       : libx11
version    : 1.7.5
release    : 34
source     :
    - https://www.x.org/releases/individual/lib/libX11-1.7.5.tar.gz : 78992abcd2bfdebe657699203ad8914e7ae77025175460e04a1045387192a978
license    : MIT
component  : xorg.library
summary    : Core X11 protocol client library
description: |
    Core X11 protocol client library
emul32     : yes
optimize   :
    - speed
    - lto
builddeps  :
    - pkgconfig32(xau)
    - pkgconfig32(xcb)
    - pkgconfig32(xdmcp)
    - pkgconfig32(xtrans)
    - pkgconfig(xproto)
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
