name        : libx11
version     : 1.6.3
release     : 9
source      :
    - http://xorg.freedesktop.org/releases/individual/lib/libX11-1.6.3.tar.gz : 0b03b9d22f4c9e59b4ba498f294e297f013cae27050dfa0f3496640200db5376
license     :
    - MIT
summary     : Core X11 protocol client library
builddeps   :
    - pkgconfig(xdmcp)
    - pkgconfig(xcb)
    - pkgconfig32(xcb)
    - pkgconfig(xau)
    - pkgconfig32(xau)
    - pkgconfig(kbproto)
    - pkgconfig(inputproto)
    - pkgconfig(xextproto)
    - pkgconfig(xtrans)
    - glibc-32bit-devel
    - libgcc-32bit
emul32      : yes
description : |
    Core X11 protocol client library
setup      : |
    %configure --prefix=/usr \
               --disable-static
build      : |
    %make
install    : |
    %make_install
    %make clean
