name       : libx11
version    : 1.6.4
release    : 14
source     :
    - https://www.x.org/releases/individual/lib/libX11-1.6.4.tar.gz : 5d7fbb9e15c27900ea8963218a59750b674a8d7c94161b66e96fcfbdaa1c6263
license    :
    - MIT
summary    : Core X11 protocol client library
component  : xorg.library
builddeps  :
    - pkgconfig(xdmcp)
    - pkgconfig(xcb)
    - pkgconfig32(xcb)
    - pkgconfig(xau)
    - pkgconfig32(xau)
    - pkgconfig(kbproto)
    - pkgconfig(inputproto)
    - pkgconfig(xextproto)
    - pkgconfig(xtrans)
    - pkgconfig(xf86bigfontproto)
    - glibc-32bit-devel
    - libgcc-32bit
emul32     : yes
optimize   : speed
description: |
    Core X11 protocol client library
setup      : |
    %configure --prefix=/usr \
               --disable-static
build      : |
    %make
install    : |
    %make_install
