name       : libx11
version    : 1.6.9
release    : 22
source     :
    - https://www.x.org/releases/individual/lib/libX11-1.6.9.tar.bz2 : 9cc7e8d000d6193fa5af580d50d689380b8287052270f5bb26a5fb6b58b2bed1
license    : MIT
component  : xorg.library
summary    : Core X11 protocol client library
description: |
    Core X11 protocol client library
builddeps  :
    - pkgconfig32(xau)
    - pkgconfig32(xcb)
    - pkgconfig32(xdmcp)
    - pkgconfig32(xtrans)
    - pkgconfig(inputproto)
    - pkgconfig(kbproto)
    - pkgconfig(xextproto)
    - pkgconfig(xf86bigfontproto)
emul32     : yes
optimize   :
    - speed
    - lto
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
