name       : libx11
version    : 1.6.5
release    : 15
source     :
    - https://www.x.org/releases/individual/lib/libX11-1.6.5.tar.gz : 3abce972ba62620611fab5b404dafb852da3da54e7c287831c30863011d28fb3
license    :
    - MIT
summary    : Core X11 protocol client library
component  : xorg.library
builddeps  :
    - pkgconfig(xdmcp)
    - pkgconfig(xcb)
    - pkgconfig32(xcb)
    - pkgconfig(xau)
    - pkgconfig32(xau)
    - pkgconfig(kbproto)
    - pkgconfig(inputproto)
    - pkgconfig(xextproto)
    - pkgconfig(xtrans)
    - pkgconfig(xf86bigfontproto)
    - glibc-32bit-devel
    - libgcc-32bit
emul32     : yes
optimize   : speed
description: |
    Core X11 protocol client library
setup      : |
    %configure --prefix=/usr \
               --disable-static
build      : |
    %make
install    : |
    %make_install
