name       : libx11
version    : 1.8.2
release    : 38
source     :
    - https://www.x.org/releases/individual/lib/libX11-1.8.2.tar.gz : f1bc56187bee0f830e1179ac5068ac93b78c51ace94eb27702ffb2efd116587b
license    : MIT
component  : xorg.library
summary    : Core X11 protocol client library
description: |
    Core X11 protocol client library
emul32     : yes
mancompress: yes
optimize   :
    - speed
    - lto
builddeps  :
    - pkgconfig32(xau)
    - pkgconfig32(xcb)
    - pkgconfig32(xdmcp)
    - pkgconfig32(xtrans)
    - pkgconfig(xproto)
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
