name       : libx11
version    : 1.6.10
release    : 23
source     :
    - https://www.x.org/releases/individual/lib/libX11-1.6.10.tar.bz2 : af48626989b8515c994777896bd7b7ba2bd5b1ef4e1efaee0a55d8852bbe6226
license    : MIT
component  : xorg.library
summary    : Core X11 protocol client library
description: |
    Core X11 protocol client library
builddeps  :
    - pkgconfig32(xau)
    - pkgconfig32(xcb)
    - pkgconfig32(xdmcp)
    - pkgconfig32(xtrans)
    - pkgconfig(inputproto)
    - pkgconfig(kbproto)
    - pkgconfig(xextproto)
    - pkgconfig(xf86bigfontproto)
emul32     : yes
optimize   :
    - speed
    - lto
setup      : |
    %patch -p1 < $pkgfiles/Fix-size-calculation-in-_XimAttributeToValue.patch
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
